---
title: "data-quality"
format: html
---

## Quick Data Summary ising 'skimr' and 'visdat'

```{r}
install.packages("skimr")
library(skimr)
library(readr)
library(dplyr)
library(lubridate)
library(pointblank)
library(ggplot2)
library(visdat)
```

```{r}
bg_chem <- read_csv("../data/BGchem2008data.csv")
```

```{r}
skim(bg_chem)
```

```{r}
bg_chem %>%
  select(Station, O2) %>%
  group_by(Station) %>% 
  skim() # works on grouped variables
```

```{r}
bg_chem_clean <- read_csv("../data/BGchem2008data.csv", na = "-99")

```

```{r}

vis_dat(bg_chem_clean, facet = Station) + theme(
  axis.text.x = element_text(angle = 45, vjust = 0)
) 
```

```{r}
bg_chem %>% 
    col_vals_gt(columns = O2, value = 0, na_pass = TRUE)

# helpful in a data analysis pipeline to immediately halt analysis and throw an error

```

```{r}
# not bg_chem_final isnt made
bg_chem_final <- bg_chem %>% 
    col_vals_gt(columns = O2, value = 0, na_pass = TRUE) %>% 
    mutate(important_metric = O2 * 0.321)
```

```{r}


bg_chem %>% 
    create_agent() %>% 
    col_vals_gt(vars(O2, NO3, NO2, NH4, P, Si), value = 0, na_pass = TRUE) %>% 
    col_vals_between(columns = vars(CTD_Salinity, Bottle_Salinity), left = 0, right = 42, na_pass = TRUE) %>% 
    col_vals_between(Latitude, left = -90, right = 90) %>%
    col_vals_between(Longitude, left = -180, right = 180) %>% 
    interrogate()

al <- action_levels(warn_at = 1, stop_at = 10)

bg_chem %>% 
    create_agent(actions = al) %>% 
    col_vals_gt(vars(O2, NO3, NO2, NH4, P, Si), value = 0, na_pass = TRUE) %>% 
    col_vals_between(columns = vars(CTD_Salinity, Bottle_Salinity), left = 0, right = 42, na_pass = TRUE) %>% 
    col_vals_between(Latitude, left = -90, right = 90) %>%
    col_vals_between(Longitude, left = -180, right = 180) %>% 
    interrogate()

#pass values to specific variables

al_latlon <- action_levels(warn_at = 1, stop_at = 5)

bg_chem_clean %>% 
    create_agent(actions = al) %>% 
    col_vals_gt(vars(O2, NO3, NO2, NH4, P, Si), value = 0, na_pass = TRUE) %>% 
    col_vals_between(columns = vars(CTD_Salinity, Bottle_Salinity), left = 0, right = 42, na_pass = TRUE) %>% 
    col_vals_between(Latitude, left = -90, right = 90, actions = al_latlon) %>%
    col_vals_between(Longitude, left = -180, right = 180, actions = al_latlon) %>% 
    interrogate()
```
